-- Common special character pair spacing adjustments (for kerning)
-- no need for "j" as difference is reduced for all "j"s
specialPairs = {
    ["fa"] = -6,
    ["fc"] = -6,
    ["fd"] = -6,
    ["fe"] = -6,
    ["ff"] = -6,
    ["fg"] = -6,
    ["fi"] = -5,
    ["fj"] = -3,
    ["fm"] = -6, 
    ["fn"] = -6, 
    ["fo"] = -6, 
    ["fp"] = -6,
    ["fq"] = -6,
    ["fr"] = -6,
    ["fs"] = -6,
    ["fu"] = -6,
    ["fv"] = -6,
    ["fw"] = -6,
    ["fx"] = -6,
    ["fy"] = -6,
    ["fz"] = -6,
    ["AV"] = -15,
    ["AW"] = -15,
    ["AM"] = -10,
    ["AN"] = -10,
    ["To"] = -10,
    ["Ta"] = -10,
    ["Te"] = -10,
    ["Th"] = -10,
    ["Yo"] = -12,
    ["Ye"] = -12,
    ["Wi"] = -8,
    ["Wa"] = -8,
    ["Wo"] = -8,
    ["We"] = -8,
    ["Ly"] = -8,
    ["Lo"] = -6,
    ["Li"] = -4,
    ["La"] = -4,
    ["Ko"] = -6,
    ["Ki"] = -4,
    ["/1"] = -3,
    ["/i"] = -3,
}
return specialPairs
